[project]
name = "meal-planner-agent"
version = "0.1.0"
description = "A meal planner agent with CrewAI"
readme = "README.md"
requires-python = "==3.12.10"
dependencies = [
    "crewai>=0.193.2",
    "dotenv>=0.9.9",
    "requests>=2.32.5",
]
